ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS low_balance_threshold REAL DEFAULT 100,
ADD COLUMN IF NOT EXISTS font_family TEXT DEFAULT 'PLUS_JAKARTA',
ADD COLUMN IF NOT EXISTS animation_intensity TEXT DEFAULT 'MEDIUM',
ADD COLUMN IF NOT EXISTS biometric_lock_timeout INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS sound_effects_enabled INTEGER DEFAULT 1;
