
import React from 'react';
import {
  Home,
  Wallet,
  PieChart,
  Settings,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  RefreshCcw,
  ShieldCheck,
  TrendingUp,
  Briefcase,
  Heart,
  ShoppingBag,
  Zap,
  Coffee,
  Plane,
  Utensils,
  Moon,
  Sun,
  Car,
  Activity,
  User,
  MoreHorizontal,
  BookOpen,
  Gamepad2,
  Stethoscope,
  Scissors,
  Landmark,
  Bitcoin,
  Building,
  Umbrella,
  Baby,
  Dumbbell,
  Smartphone,
  Globe,
  Bus,
  Fuel,
  Gift,
  Tv,
  Music,
  Ticket,
  Palette,
  Watch,
  Shirt,
  Trash2,
  Droplet,
  Flame,
  Wifi,
  Dog,
  ShieldPlus,
  HeartHandshake,
  Church,
  Calculator,
  Laptop,
  Hammer,
  Trees,
  Gem,
  Coins,
  Receipt,
  PiggyBank,
  Layers
} from 'lucide-react';
import { Category, MasterCategoryType } from '../types';

export const COLORS = {
  primary: '#3B82F6',
  secondary: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  surface: '#18181B',
  background: '#0a0a0c',
  accent: '#A855F7',
  muted: '#71717A'
};

// DEPRECATED: Categories are now fetched from Supabase 'categories' table.
export const GLOBAL_CATEGORIES: Category[] = [];

export const ICON_MAP: Record<string, React.ReactNode> = {
  Home: <Home size={20} />,
  Wallet: <Wallet size={20} />,
  PieChart: <PieChart size={20} />,
  Settings: <Settings size={20} />,
  Plus: <Plus size={20} />,
  ArrowUpRight: <ArrowUpRight size={20} />,
  ArrowDownLeft: <ArrowDownLeft size={20} />,
  RefreshCcw: <RefreshCcw size={20} />,
  ShieldCheck: <ShieldCheck size={20} />,
  TrendingUp: <TrendingUp size={20} />,
  Briefcase: <Briefcase size={20} />,
  Heart: <Heart size={20} />,
  ShoppingBag: <ShoppingBag size={20} />,
  Zap: <Zap size={20} />,
  Coffee: <Coffee size={20} />,
  Plane: <Plane size={20} />,
  Utensils: <Utensils size={20} />,
  Moon: <Moon size={20} />,
  Sun: <Sun size={20} />,
  Car: <Car size={20} />,
  Activity: <Activity size={20} />,
  User: <User size={20} />,
  MoreHorizontal: <MoreHorizontal size={20} />,
  BookOpen: <BookOpen size={20} />,
  Gamepad2: <Gamepad2 size={20} />,
  Stethoscope: <Stethoscope size={20} />,
  Scissors: <Scissors size={20} />,
  Landmark: <Landmark size={20} />,
  Bitcoin: <Bitcoin size={20} />,
  Building: <Building size={20} />,
  Umbrella: <Umbrella size={20} />,
  Baby: <Baby size={20} />,
  Dumbbell: <Dumbbell size={20} />,
  Smartphone: <Smartphone size={20} />,
  Globe: <Globe size={20} />,
  Bus: <Bus size={20} />,
  Fuel: <Fuel size={20} />,
  Gift: <Gift size={20} />,
  Tv: <Tv size={20} />,
  Music: <Music size={20} />,
  Ticket: <Ticket size={20} />,
  Palette: <Palette size={20} />,
  Watch: <Watch size={20} />,
  Shirt: <Shirt size={20} />,
  Trash2: <Trash2 size={20} />,
  Droplet: <Droplet size={20} />,
  Flame: <Flame size={20} />,
  Wifi: <Wifi size={20} />,
  Dog: <Dog size={20} />,
  ShieldPlus: <ShieldPlus size={20} />,
  HeartHandshake: <HeartHandshake size={20} />,
  Church: <Church size={20} />,
  Calculator: <Calculator size={20} />,
  Laptop: <Laptop size={20} />,
  Hammer: <Hammer size={20} />,
  Trees: <Trees size={20} />,
  Gem: <Gem size={20} />,
  Coins: <Coins size={20} />,
  Receipt: <Receipt size={20} />,
  PiggyBank: <PiggyBank size={20} />,
  Layers: <Layers size={20} />,
  Sparkles: <Plus size={20} className="text-blue-500" />,
};
